{% set name = "dap" %}
{% set version = "0.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source: 
  git_url: https://github.com/molinerisLab/dap.git
  git_ref: 0.2
build:
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - python >3
    - typer
    - gitpython


about:
  home: https://github.com/molinerisLab/dap
  summary: Bioinformatics projects management tool
