{% set name = "dap" %}
{% set version = "2.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source: 
  path: ../src
  
build:
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - python >3.6
    - typer


about:
  home: https://github.com/molinerisLab/dap
  summary: Bioinformatics projects management tool
